### ISSUE TITLE
Daily Targets Rework

### ISSUE THREAD

**Issue by Voltrifrodec** [Voltrifrodec/CSSBattle#5]
## Tasks
- [ ] Add missing markdown files for the daily targets.
- [ ] Move `*.html` files to the `src/html` folder.
- [ ] (*only with PLUS membership*) upload missing screenshots for solutions.
- [ ] Update `README.md` file in the `000-daily-targets` folder (update calendar).
