### ISSUE TITLE
Folder hierarchy rework - Daily Targets

### ISSUE THREAD

**Issue by Voltrifrodec** [Voltrifrodec/CSSBattle#7]
## Explanation
Move all `*.md` files to the new `src/markdown` folder to reduce the number of files in the root of `000-daily-targets` to a minimum. Also, move all the `daily-target_*.png` files to the new `src/images/target-solution` folder.
Desired result:
![image](https://github.com/Voltrifrodec/CSSBattle/assets/69749982/e052b659-9a8b-4359-aa86-9b9ab9b6d65a)

## Task List
- [x] Move the `*.md` files to the new `src/markdown` folder (exclude: _ATTEMPTS.md_, _README.md_).
- [x] Rename folder `targets` to `target-preview`.
- [x] Move all the `daily-target_*.png` files to the new `src/images/target-solution` folder.
- [x] Update paths in all of the affected Markdown files.
- [x] Update paths in the _ATTEMPT.md_.
- [x] Update paths in the _README.md_.

<br>
